version: '3.7'
volumes:
  data:
    name: data

services:
  db:
    image: mvertes/alpine-mongo
    volumes:
      - .:/ws
      - data:/data/db
    ports:
      - 27017:27017
  backend:
    image: node:12.16.1-alpine
    volumes:
      - .:/ws
    environment:
      - vidly_jwtPrivateKey=mySecureKey
    ports:
      - 3000:3000 #dev
      - 3001:3001 #test
      - 5858:5858
    working_dir: /ws/backend
    entrypoint: sh -c 'npm install; npm start'
